name: Teste de Performance com JMeter

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Configura o Node.js na versão 20
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Checkout do código do repositório
      - name: Checar repositório
        uses: actions/checkout@v3

      # Baixar e instalar JMeter 5.6.3
      - name: Baixar e instalar JMeter
        run: |
          wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.zip
          unzip apache-jmeter-5.6.3.zip
          rm apache-jmeter-5.6.3.zip

      # Rodar os testes JMeter
      - name: Rodar testes JMeter
        run: |
          # Caminho para o script de teste JMeter e arquivos necessários
          ./apache-jmeter-5.6.3/bin/jmeter -n -t path/to/test-plan.jmx -l results.jtl

      # Gerar o relatório
      - name: Gerar Relatório de Performance
        run: |
          ./apache-jmeter-5.6.3/bin/jmeter -g results.jtl -o /path/to/output-report
          
      # Enviar relatório para a pasta específica ou como artefato
      - name: Enviar relatório para o repositório
        uses: actions/upload-artifact@v3
        with:
          name: performance-report
          path: /path/to/output-report
