name: Rodar Testes JMeter

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checar repositório
        uses: actions/checkout@v2

      - name: Atualizar pacotes e instalar dependências
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk ca-certificates wget unzip

      - name: Instalar JMeter
        run: |
          wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.5.zip
          unzip apache-jmeter-5.5.zip
          sudo mv apache-jmeter-5.5 /opt/jmeter
          echo "export PATH=\$PATH:/opt/jmeter/bin" >> ~/.bashrc
          source ~/.bashrc

      - name: Verificar instalação do JMeter
        run: |
          jmeter -v

      - name: Rodar testes JMeter
        run: |
          jmeter -n -t caminho/para/seu/arquivo.jmx -l resultado.jtl
          
      - name: Upload Relatório JMeter
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: resultado.jtl
