name: Teste de Performance com JMeter e Latency Lingo

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Configurar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Checar repositório
      - name: Checar repositório
        uses: actions/checkout@v3

      # Baixar e instalar JMeter
      - name: Baixar e instalar JMeter
        run: |
          wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.zip
          unzip apache-jmeter-5.6.3.zip
          rm apache-jmeter-5.6.3.zip

      # Rodar os testes JMeter
      - name: Rodar testes JMeter
        run: |
          ./apache-jmeter-5.6.3/bin/jmeter -n -t jmeter-tests/test-plan.jmx -l results.jtl

      # Enviar resultados para o Latency Lingo via API
      - name: Enviar resultados para o Latency Lingo
        run: |
          curl -X POST https://api.latencylingo.com/results \
            -H "Authorization: Bearer ${{ secrets.LATENCY_LINGO_API_KEY }}" \
            -F "file=@results.jtl" \
            -F "testName=Test_Performance"

      # Gerar Relatório de Performance
      - name: Gerar Relatório de Performance
        run: |
          ./apache-jmeter-5.6.3/bin/jmeter -g results.jtl -o ./output-report

      # Enviar relatório para o repositório
      - name: Enviar relatório para o repositório
        uses: actions/upload-artifact@v3
        with:
          name: performance-report
          path: ./output-report
